### ISSUE TITLE
Сделать валидации полей у модели клиента

### ISSUE THREAD

**Issue by sdavydouski** [mammonbank/webapp#10]
в core/models/client нужно добавить пару регулярок для проверки некоторых полей: проверка на то, что значение является валидным номером телефона, номером паспорта ну и подобное. Подробности в комментах.

**Comment by sdavydouski** [comment]
Работать нужно в ветке 2fa

**Comment by Tocher** [comment]
@wiranoid вроде 2fa скоро будет в мастере.
- надо добавить проверку кириллических символов (в коде в TODO помечено)

**Comment by sdavydouski** [comment]
да, я в курсах)
просто надеялся что @kosyakovii сделает это пораньше
ну короч как обычно все.
@kosyakovii если что, теперь в ветке master
